# Common distractor pools
WEAPON_POOL = ["Sword", "Claymore", "Polearm", "Bow", "Catalyst"]

ELEMENT_POOL = ["Anemo", "Geo", "Electro", "Dendro", "Hydro", "Pyro", "Cryo"]

REGION_POOL = ["Mondstadt", "Liyue", "Inazuma", "Sumeru", "Fontaine", "Natlan", "Snezhnaya"]

TITLE_POOL = ["Tasteful Excellence", "In the Wake of Wandering Winds", "Tempered in Molten Stone", "Strength in Serenity", "Embrace of Enchanting Dreams", 
              "Spring Woven from Jade", "Night-Igniting Flame", "Obsidian Opalstar", "Skyborne Arbiter", "Shadow of Night-Wind", "Ardent Flames Forge the Soul", 
              "Turnfire Hunt", "Mottled Gold Yet Unsmelted", "Splish-Splash Wavechaser", "A Thousand Scents Traced", "Wondrous Dragonheir", "Wisdom's Measure", 
              "Candlebearer, Shadowhunter", "Dire Balemoon", "Thundering Seamstress", "Leonine Vanguard", "Passerine Herald", "Executor of Justice", 
              "Helm of the Radiant Rose", "Lens of Verity", "Endless Solo of Solitude", "Emissary of Solitary Iniquity", "Ordainer of Inexorable Judgement", 
              "Yearning for Unseen Depths", "Elegance in the Shadows", "Spectacle of Phantasmagoria", "Cat Upon the Eaves", "Empyrean Reflection", "Beyond Mortality", 
              "Coordinates of Clear Frost", "Flame-Mane", "Burgeoning Grace", "Admonishing Instruction", "Eons Adrift", "Enigmatic Machinist", "Fantastical Evening Star", 
              "Physic of Purity", "Dance of Lotuslight", "Judicator of Secrets", "Golden Vow", "Treasure of Dream Garden", "Sprout of Rebirth", "Verdant Strider", 
              "Analytical Harmony", "Mender of Tribulations", "Valley Orchid", "Pillar of Fortitude", "Astute Amusement", "Lonesome Transcendence", "Stage Lucinda", 
              "Canine Warrior", "Hanamizaka Heroics", "Protector From Afar", "Pearl of Wisdom", "Plane of Euthymia", "Crowfeather Kaburaya", "Saviour From Another World", 
              "Frolicking Flames", "Mujina Ninja", "Frostflake Heron", "Scarlet Leaves Pursue Wild Waves", "Dance of Shimmering Waves", "Wise Innocence", "Thorny Benevolence", 
              "Fragrance in Thaw", "Vigilant Yaksha", "Plenilune Gaze", "Kreideprinze", "Vago Mundo", "Blazing Rift", "Childe", "Katzlein Cocktail", "Dandelion Knight", 
              "Witch of the Purple Rose", "Shining Idol", "Frostwind Swordsman", "Dark Side of Dawn", "Wolf Boy", "Gliding Champion", "Windborne Bard", "Exquisite Delicacy", 
              "Uncrowned Lord of the Ocean", "Juvenile Galant", "Eclipsing Star", "Fleeing Sunlight", "Prinzessin der Verurteilung!", "Trial by Fire", "Chivalric Blossom", 
              "Icy Ressurection", "Frozen Ardor", "Astral Reflection", "Driving Thunder", "Harmless Sweetie"]

SPECIAL_DISH_POOL = ["Clink-Clank Confectionery Cup", "Woodland Dream", "Ideal Circumstance", "Satiety Gel", "Outrider's Champion Steak!", 
                     "Way of the Strong", "Hearthfire's Trail", "Heat-Quelling Soup", "Spicy Stew", "Flash-Fried Filet", 
                     "Teyvat Charred Egg", "Utmost Care", "Exclusive Scoop: Gourmet Column", "Moment of Respite", 
                     "Sin: The Kind that Doesn't Need to be Dealt With", "'Fashion Show'", "Cold Noodles with Mountain Delicacies", 
                     "Secret Art", "'Tagged and Bagged'", "Yearning", "Duel Soul", "'Chatter of Joyful Nights'", "Goldflame Tajine", 
                     "'Once Upon a Time in Mondstadt'", "Definitely Not Bar Food!", "Show Me the Mora", "Apple Stew (Trial Version)", 
                     "A Fragrant Feast of Flavors", "Gateau Debord: Magnifique", "Stormcrest Pie", 
                     "Traditionally-Made Charcoal-Baked Ajilenakh Cake", "Die Heilige Sinfonie", "Long Night Alight", 
                     "\"Seabird's Sojourn\"", "\"Pour la Justice\"", "Yummy Yum Cha", "Prosperous Peace", "Victorious Legend", 
                     "Ghostly March", "Gold-Standard Healthy Meal", "Emotional Support", "Thunderclap Slash!", 
                     "\"After-Class Practice\"", "Invigorating Pizza", "Impeccably Organized", "All-Weather Beauty", "Fruity Skewers", 
                     "\"Snow on the Hearth\"", "Quiet Elegance", "The Endeavor", "Survival Grilled Fish", "Saurian Hunter's Reward", 
                     "Energizing Bento", "Fish-Flavored Toast", "Faith Eternal", "Omurice Waltz", "Jade-Cut Flowers", "Whisper in the Woods", 
                     "Extravagant Slumber", "Mysterious Bolognese", "A Leisurely Sip", "Cubic Tricks", "Hymn of Gathered Flame", 
                     "Surveyor's Breakfast Sandwich", "Der Weisheit Letzter Schluss (Life)", "Pass the Luck", "Halvamazd", 
                     "\"Pick What You Like!\"", "Secrets Exchanged", "\"Consommé Purete\"", "Swirling Steps", "Qiankun Mora Meat", 
                     "Lighter-Than-Air Pancake", "Honey-Glazed Ceviche", "No Tomorrow", "Puppy-Paw Hash Brown", "Dinner of Judgment", 
                     "A Stunning Stratagem", "Dizziness-Be-Gone no Jutsu Version 2.0", "Super-Dee-Duper Delicious Meat Roll", 
                     "Heartstring Noodles", "The Only Truth", "Well-Balanced Meal", "\"Abyssal Bounty\"", "Nutritious Meal (V.593)", 
                     "A Prize Catch", "\"Warmth\"", "Forest Watcher's Choice", "Mt. Mushroom (For One)", "A Buoyant Breeze", 
                     "Shimi Chazuke", "Secret Sauce BBQ Ribs", "Wanmin Restaurant's Boiled Fish", "Encompassing Gladness", 
                     "\"Sweet Dream\"", "Fruit-Flavored Milk Candies", "All-Delicacy Parcels", "Rockin' Riffin' Chicken!", 
                     "Fukuuchi Udon", "\"My Way\"", "Qingce Household Dish", "Dew-Dipped Shrimp", "Summer Festival Fish", 
                     "Dreams of Healing", "Cloud-Shrouded Jade", "Slow-Cooked Bamboo Shoot Soup"]

CONSTELLATION_POOL = ["Viator", "Cistellula Mira", "Princeps Cretaceus", "Vultur Volans", "Nora Fortis", "Lepus", "Taurus Iracundus", "Ignis Purgatorius", "Lagenaria", 
                      "Crater", "Victor Mare", "Rota Calamitas", "Sagitta Scutum", "Hualina Veritas", "Vultur Gryphus", "Sclopetum Ensiferum", "Cisoria", "Nubis Caesor", 
                      "Patina Anavatlaca", "Rapperia", "Leptailurus Cervarius", "Lupus Aureus", "Cantus Choralis", "Mantichora", "Noctua", "Feles", "Magicae Lucerna", 
                      "Draco Rubedo", "Pomum de Ambra", "Dulciaria Structura", "Aphros Delos", "Flosculi Implexi", "Corvus", "Laterna Vigilis", "Automaton", 
                      "Animula Choragi", "Leo Expergiscens", "Sinae Unicornis", "Canis Bellatoris", "Papilio Charontis", "Carnotaurus", "Catena Opele", "Oriolus", 
                      "Vanilla Planifolia", "Fragum", "Leo Minor", "Ochotona Princeps", "Acer Palmatum", "Pavo Ocellus", "Grus Nivis", "Cypressus Custos", "Paradisaea", 
                      "Trulla Cementarii", "Chimaera Alebriius", "Arcella", "Trifolium", "Flabellum", "Tribulatio Demptio", "Hirundo Lazuli", "Cerva Nivea", "Luscinia", 
                      "Tempus Fugit", "Viatrix", "Felis Alba", "Felis Fuscus", "Sol Invictus", "Palumbus", "Astrolabos", "Phoca Neomonachus", "Sapientia Oromasdis", 
                      "Rosa Multiflora", "Ludus Latrunculorum", "Leviathan Judicator", "Lotos Somno", "Opus Aequilibrium", "Parma Cordis", "Vampyrum Spectrum",
                      "Pristina Nola", "Imperatrix Umbrosa", "Lupus Minor", "Spinea Corona", "Dracaena Somnolenta", "Nyctereutes Minor", "Basileos Delta", 
                      "Crista Doloris", "Cervus Minor", "Nereides", "Crystallina", "Ampulla", "Monoceros Caeli", "Rubeum Scutum", "Vulpes Zerda", "Mascara Luctatori", 
                      "Carmen Dei", "Peregrinus", "Cerberus", "Trulla", "Grus Serena", "Alatus Nemeseos", "Panthera Ocelota", "Fabulae Textile", "Fila Ignium", 
                      "Divina Vulpes", "Bestia Iustitia", "Osmanthus", "Umbrabilis Orchis", "Carassius Auratus", "Tapirus Somniator", "Opera Grandis", "Lapis Dei", "Equa Alba"]

BIRTHDAY_POOL = ["Player's Choice", "January 3rd", "January 5th", "January 6th", "January 9th", "January 10th", "January 18th", 
                 "January 20th", "January 22nd", "January 24th", "February 2nd", "February 2nd", "February 11th", "February 14th", 
                 "February 22nd", "February 29th", "March 1st", "March 3rd", "March 6th", "March 10th", "March 13th", "March 14th", 
                 "March 14th", "March 16th", "March 21st", "March 23rd", "March 26th", "March 30th", "April 2nd", "April 4th", 
                 "April 7th", "April 10th", "April 11th", "April 17th", "April 20th", "April 22nd", "April 25th", "April 30th", 
                 "May 3rd", "May 8th", "May 9th", "May 18th", "May 21st", "May 25th", "May 27th", "May 31st", "June 1st", 
                 "June 1st", "June 8th", "June 9th", "June 16th", "June 21st", "June 23rd", "June 26th", "June 27th", 
                 "July 5th", "July 9th", "July 14th", "July 15th", "July 20th", "July 24th", "July 27th", "July 27th", 
                 "July 28th", "August 3rd", "August 8th", "August 10th", "August 11th", "August 16th", "August 17th",
                 "August 20th", "August 22nd", "August 26th", "August 28th", "August 31st", "September 7th", "September 9th", 
                 "September 13th", "September 20th", "September 21st", "September 22nd", "September 24th", "September 28th", 
                 "October 9th", "October 13th", "October 14th", "October 16th", "October 19th", "October 25th", "October 27th", 
                 "October 29th", "October 31st", "November 2nd", "November 5th", "November 11th", "November 15th", "November 20th", 
                 "November 23rd", "November 26th", "November 30th", "December 2nd", "December 3rd", "December 10th", "December 18th", 
                 "December 19th", "December 21st", "December 22nd", "December 29th", "December 31st"]

RELEASED_VERSION_POOL = ["vLuna I", "v1.2", "v3.4", "v2.1", "v1.0", "v2.3", "v4.6", "v3.6", "v1.0", "v1.0", "v1.0", "v3.1", "v4.2", "v5.2", 
                         "v4.3", "v4.5", "v1.0", "v5.3", "v4.7", "v3.0", "v3.1", "v5.7", "v3.5", "v1.0", "v1.1", "v3.0", "vLuna III", "v4.8", 
                         "v5.6", "v1.5", "v3.3", "v1.0", "vLuna I", "v4.0", "v4.2", "v4.4", "v1.2", "v2.3", "v1.3", "v5.5", "v5.6", "v5.8", 
                         "vLuna III", "v1.0", "v5.0", "v1.6", "v1.0", "v2.0", "v2.6", "v3.6", "v1.0", "v5.0", "v3.7", "v1.0", "v2.1", "v2.7", 
                         "v5.3", "vLuna I", "v3.2", "v1.0", "v4.0", "v4.0", "v5.3", "v3.5", "v1.0", "v5.0", "v3.2", "v4.3", "vLuna II", 
                         "v4.1", "v3.1", "v1.0", "v1.0", "v5.2", "v1.0", "v2.1", "v1.0", "v1.4", "v2.1", "v2.0", "v4.7", "v2.4", "v2.8", 
                         "v4.7", "v5.7", "v1.0", "v1.1", "v2.2", "v3.0", "v1.0", "v5.5", "v1.0", "v3.3", "vLuna II", "v4.1", "v1.0", 
                         "v4.4", "v1.3", "v5.1", "v1.0", "v1.1", "v2.5", "v1.5", "v3.4", "v2.7", "v2.0", "v5.4", "v2.4", "v1.1"]

ENGLISH_VA_POOL = ["Annabel Brook", "Khoi Dao", "Nazeeh Tarsha", "Giselle Fernandez", "Kelly Baskin", "Max Mittelman", "Erin Yvette", 
                   "Sean Durrie", "Laura Stahl", "Allegra Clark", "Cristina Vee Valenzuela", "Shara Kirby (Pre-Luna II)", 
                   "Maya Aoki Tuttle", "Lauren Amante", "Erica Lindbeck", "Brittany Lauda", "Beau Bridgland", "Skyler Davenport", 
                   "Crystal Lee", "Christina Costello", "Alejandro Saab", "Aileen Mythen", "Amber May", "Sean Chiplock", 
                   "Dina Sherman", "Anjali Kunapaneni", "Laurie Kynaston", "Amber Aviles", "Emily Cass", "Suzie Yeung", "Chandni Parekh", 
                   "Brittany Cox", "Nic Olsen", "Paul Castro Jr.", "Amber Lee Connors", "Caleb Yen", "Jennifer Losi", "Cory Yee", 
                   "Brianna Knickerbocker", "Katrina Salisbury", "Jonny Loquasto", "Angelina Danielle Cama", "Sonya Krueger", 
                   "Stephanie Southerland", "Kristen McGuire", "Mark Whitten", "Josey Montana McCoy", "Erica Mendez", "Chris Hackney", 
                   "Ben Balmaceda", "Kayli Mills (Pre-5.7)", "Jacob Takanashi", "Julia Gu", "Poonam Basu", "Jeannie Tirado", 
                   "Kira Buckland", "Anna Devlin", "Alexandra Guelff", "Ashely Biski", "Mara Junot", "Anairis Quiñones", "Daman Mills", 
                   "Katiana Sarkissian", "Robb Moreira", "Felecia Angelle", "Cassandra Lee Morris", "Kimberley Anne Campbell", 
                   "Brenna Larsen", "Ashleigh Haddad", "Ray Chase", "Dani Chambers", "Erin Ebers", "Laura Faye Smith", "Nathan Nokes", 
                   "Christie Cate", "Anne Yatco", "Todd Haberkorn", "Elizabeth Maxwell", "Risa Mei", "Lilypichu (Lily Ki)", 
                   "Zeno Robinson", "Chelsea Kwoka", "Kieran Regan", "Sarah Williams", "Cat Protano", "Valeria Rodriguez (Pre-5.8)", 
                   "Griffin Burns", "Christian Banas", "Zachary Gordon", "Zach Aguilar", "Jane Jackson", "Erika Harlacher", 
                   "Patrick Pedraza", "Edward Stoneguard", "Joe Zieja", "Jackie Lastra", "Stephanie Panisello", "Laila Berzins", 
                   "Elizabeth Dean", "Cristina Vee Valenzuela", "Laura Stahl", "Ratana", "Lizzie Freeman", "Kelsey Jaffer", 
                   "Laura Post", "Jenny Yokobori", "Naomi McDonald", "Judy Alice Lee", "Keith Silverstein"]

JAPANESE_VA_POOL = ["Takamori Natsumi (高森奈津美)", "Nojima Kenji (野島健児)", "Umehara Yuuichirou (梅原裕一郎)", "Takagaki Ayahi (高垣彩陽)", 
                    "Iwami Manaka (石見舞菜香)", "Nishikawa Takanori (西川貴教)", "Mori Nanako (森なな子)", "Yusa Koji (遊佐浩二)", 
                    "Kitou Akari (鬼頭明里)", "Koshimizu Ami (小清水亜美)", "Ousaka Ryouta (逢坂良太)", "Yuzuki Ryoka (柚木涼香)",
                    "Waki Azumi (和氣あず未)", "Kaida Yuuko (甲斐田裕子)", "Shimoji Shino (下地紫野)", "Taketatsu Ayana (竹達彩奈)", 
                    "Saito Soma (斉藤壮馬)", "Tano Asami (田野アサミ)", "Ishikawa Yui (石川由依)", "Maekawa Ryoko (前川涼子)", 
                    "Irino Miyu (入野自由)", "Yamamoto Kazutomi (山本和臣)", "Fukuhara Ayaka (福原綾香)", "Ono Kensho (小野賢章)", 
                    "Izawa Shiori (井澤詩織)", "Kaneda Tomoko (金田朋子)", "Kobayashi Chiaki (小林 千晃)", "Hikasa Yoko (日笠陽子)", 
                    "Satō Satomi (佐藤聡美)", "Satou Rina (佐藤利奈)", "Horie Yui (堀江由衣)", "Uchida Maaya (内田真礼)", 
                    "Nakamura Yūichi (中村悠一)", "Toki Shunichi (土岐隼一)", "Minase Inori (水瀬いのり)", "Komatsu Shouhei (小松昌平)", 
                    "Ueda Reina (上田麗奈)", "Hatanaka Tasuku (畠中祐)", "Takahashi Rie (高橋李依)", "Ohashi Ayaka (大橋彩香)", 
                    "Terashima Junta (寺島惇太)", "Nakajima Megumi (中島愛)", "Inagaki Konomi (稲垣好)", "Saitou Chiwa (斎藤千和)", 
                    "Kubo Yurika (久保ユリカ)", "Shimazaki Nobunaga (島﨑信長)", "Toriumi Kousuke (鳥海浩輔)", "Hayami Saori (早見沙織)", 
                    "Ishida Akira (石田彰)", "Uchida Yuma (内田雄馬)", "Kitamura Eri (喜多村英梨)", "Sugiyama Noriaki (杉山紀彰)", 
                    "Suzushiro Sayumi (鈴代紗弓)", "Kuno Misaki (久野美咲)", "Seto Asami (瀬戸麻沙美)", "Mizuhashi Kaori (水橋かおり)", 
                    "Wakayama Shion (若山詩音)", "Kuwashima Houko (桑島法子)", "Tomita Miyu (富田美憂)", "Tanaka Rie (田中理恵)", 
                    "Sasahara Yu (篠原侑)", "Shimono Hiro (下野紘)", "Komatsu Mikako (小松未可子)", "Sanpei Yūko (三瓶由布子)", 
                    "Kohara Konomi (小原好美)", "Toyama Nao (東山奈央)", "Tamura Yukari (田村ゆかり)", "Toyosaki Aki (豊崎愛生)", 
                    "Mizuki Nana (水樹 奈々)", "Kamiya Hiroshi (神谷浩史)", "Kanemoto Hisako (金元寿子)", "Ohara Sayaka (大原さやか)", 
                    "Takao Kanon (高尾奏音)", "Kondo Takashi (近藤隆)", "Tamura Yukari (田村ゆかり)", "Sawashiro Miyuki (沢城みゆき)", 
                    "Uchiyama Kouki (内山昂輝)", "Kakuma Ai (加隈亜衣)", "Mimori Suzuko (三森すずこ)", "Suzaki Aya (洲崎綾)", 
                    "Chiba Shoya (千葉翔也)", "Kawasumi Ayako (川澄綾子)", "Iguchi Yuuichi (井口祐一)", "Kino Hina (木野日菜)", 
                    "Noto Mamiko (能登麻美子)", "Fujita Akane (藤田茜)", "Kimura Ryohei (木村良平)", "Morita Masakazu (森田成一)", 
                    "Kobayashi Sanae (小林沙苗)", "Horie Shun (堀江瞬)", "Ichimichi Mao (M・A・O)", "Murase Ayumu (村瀬歩)", 
                    "Kakihara Tetsuya (柿原徹也)", "Matsuoka Yoshitsugu (松岡禎丞)", "Ono Daisuke (小野大輔)", "Ozawa Ari (小澤亜李)", 
                    "Nakatomi Mana (中臣真菜)", "Matsuoka Yoshitsugu (松岡禎丞)", "Fairouz Ai (ファイルーズあい)", "Minagawa Junko (皆川純子)", 
                    "Takahashi Chiaki (たかはし智秋)", "Sakura Ayane (佐倉綾音)", "Hanamori Yumiri (花守ゆみり)", "Kadowaki Mai (門脇舞以)", 
                    "Endou Aya (遠藤綾)", "Ueda Kana (植田佳奈)", "Aizawa Saya (会沢紗弥)", "Koiwai Kotori (小岩井ことり)", 
                    "Maeno Tomoaki (前野智昭)"]

